// Auto-generated by ci/generate_contract_bindings.py. DO NOT EDIT.
// Source schemas: contracts/enums/*.json
// Generator version: 1.0.0-bootstrap
// Deterministic command: python ci/generate_contract_bindings.py

package org.sih26168.contracts.enums

enum class AlignmentStatusV1 {
    UNINITIALIZED,
    VALID,
    UNCERTAIN,
    SLIP_SUSPECTED,
}

enum class DisplayModeV1 {
    LIVE_DEVICE,
    DETERMINISTIC_REPLAY,
}

enum class HealthIntegrityStateV1 {
    HEALTHY,
    DEGRADED,
    UNAVAILABLE,
    CANDIDATE_RETURN,
}

enum class MapStatusV1 {
    MISSING,
    NO_CANDIDATE,
    AMBIGUOUS,
    CLEAR,
    FAILED,
}

enum class ModelStatusV1 {
    DISABLED,
    LOADING,
    SHADOW,
    ELIGIBLE,
    REJECTED,
    FAILED,
}

enum class NavigationModeV1 {
    INITIALIZING,
    GNSS_AIDED,
    DEGRADED,
    BLACKOUT_DR,
    REACQUIRING,
    FAULT,
}

enum class ProvenanceClassificationV1 {
    LIVE_DEVICE,
    DETERMINISTIC_REPLAY,
}

enum class ProvenanceTypeV1 {
    LIVE_DEVICE,
    DETERMINISTIC_REPLAY,
    LIVE,
    REPLAY,
}

enum class ReacquisitionStatusV1 {
    IDLE,
    SCREENING,
    DWELL,
    ACCEPTED,
    REJECTED,
}

enum class RecordingStatusV1 {
    STARTING,
    HEALTHY,
    EVIDENCE_DEGRADED,
    LOW_STORAGE,
    INCOMPLETE,
    COMPLETE,
}

enum class SensorStatusV1 {
    AVAILABLE,
    PARTIAL,
    GAP,
    MISSING_MANDATORY,
    FAILED,
}
