import copy
import importlib.util
import json
import subprocess
import sys
import unittest
from pathlib import Path

class CodegenContractTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.root = Path(__file__).resolve().parents[3]
        cls.ci_script = cls.root / "ci/generate_contract_bindings.py"
        cls.generated_dir = cls.root / "contracts/generated"

    def test_codegen_check_mode_passes(self):
        result = subprocess.run(
            [sys.executable, str(self.ci_script), "--check"],
            cwd=self.root,
            capture_output=True,
            text=True
        )
        self.assertEqual(result.returncode, 0, f"Codegen check failed: {result.stderr}")
        self.assertIn("PASS: generated contract bindings", result.stdout)

    def test_codegen_idempotency(self):
        # Capture generated files before running
        before = {p: p.read_bytes() for p in self.generated_dir.rglob("*") if p.is_file()}

        # Run generation command
        result = subprocess.run(
            [sys.executable, str(self.ci_script)],
            cwd=self.root,
            capture_output=True,
            text=True
        )
        self.assertEqual(result.returncode, 0, f"Codegen execution failed: {result.stderr}")

        # Capture generated files after running
        after = {p: p.read_bytes() for p in self.generated_dir.rglob("*") if p.is_file()}
        self.assertEqual(before, after, "Idempotent codegen modified files unexpectedly")

    def test_contract_version_manifest(self):
        manifest_path = self.generated_dir / "contract_version.json"
        self.assertTrue(manifest_path.is_file(), "contract_version.json must exist")
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
        # Read the expected version from contracts/VERSION rather than
        # hard-coding it, so this assertion doesn't silently stop verifying
        # anything the moment the repo bumps contracts/VERSION.
        version_file = self.root / "contracts/VERSION"
        expected_version = version_file.read_text(encoding="utf-8").strip()
        self.assertEqual(data.get("contract_version"), expected_version)
        inputs = data.get("generated_from", [])
        self.assertIn("contracts/VERSION", inputs)
        self.assertIn("contracts/enums/navigation_mode_v1.json", inputs)
        self.assertIn("contracts/schemas/common/timestamp_v1.schema.json", inputs)
        self.assertEqual(inputs, sorted(inputs), "Manifest generated_from must be sorted")

    def test_generated_file_headers(self):
        for path in self.generated_dir.rglob("*"):
            if path.is_file() and path.suffix in [".hpp", ".py", ".kt"]:
                content = path.read_text(encoding="utf-8")
                self.assertIn("Auto-generated by ci/generate_contract_bindings.py. DO NOT EDIT.", content, f"Header missing in {path.name}")
                self.assertIn("Generator version: 1.0.0-bootstrap", content, f"Version missing in {path.name}")
                self.assertIn("Deterministic command: python ci/generate_contract_bindings.py", content, f"Command missing in {path.name}")

    def test_all_nine_supervisory_axes_in_generated_enums(self):
        cpp_enums = (self.generated_dir / "cpp/enums.hpp").read_text(encoding="utf-8")
        py_enums = (self.generated_dir / "python/enums.py").read_text(encoding="utf-8")
        kt_enums = (self.generated_dir / "kotlin/Enums.kt").read_text(encoding="utf-8")

        expected_enums = [
            "NavigationModeV1",
            "HealthIntegrityStateV1",
            "AlignmentStatusV1",
            "DisplayModeV1",
            "SensorStatusV1",
            "ModelStatusV1",
            "MapStatusV1",
            "ReacquisitionStatusV1",
            "RecordingStatusV1",
            "ProvenanceTypeV1",
        ]

        for enum_name in expected_enums:
            self.assertIn(f"enum class {enum_name}", cpp_enums, f"C++ missing {enum_name}")
            self.assertIn(f"class {enum_name}", py_enums, f"Python missing {enum_name}")
            self.assertIn(f"enum class {enum_name}", kt_enums, f"Kotlin missing {enum_name}")

    def test_python_models_roundtrip(self):
        # Dynamically import generated python package
        models_path = self.generated_dir / "python/models.py"
        enums_path = self.generated_dir / "python/enums.py"

        # Load enums module
        enums_spec = importlib.util.spec_from_file_location("contracts.generated.python.enums", enums_path)
        enums_mod = importlib.util.module_from_spec(enums_spec)
        sys.modules["contracts.generated.python.enums"] = enums_mod
        enums_spec.loader.exec_module(enums_mod)

        # Load models module
        models_spec = importlib.util.spec_from_file_location("contracts.generated.python.models", models_path)
        models_mod = importlib.util.module_from_spec(models_spec)
        sys.modules["contracts.generated.python.models"] = models_mod
        models_spec.loader.exec_module(models_mod)

        # Instantiate models and test round-trip serialization
        ts = models_mod.TimestampV1(epoch_ns=3456789000000, arrival_elapsed_realtime_ns=3456789000000, clock_id="CLOCK_BOOTTIME")
        ts_dict = ts.to_dict()
        self.assertEqual(ts_dict["epoch_ns"], 3456789000000)
        self.assertEqual(models_mod.TimestampV1.from_dict(ts_dict), ts)

        prov = models_mod.ProvenanceV1(
            evidence_id="ev-001",
            session_id="sess-001",
            stream_id="stream-accel",
            provenance_type=enums_mod.ProvenanceTypeV1.LIVE_DEVICE,
            synthetic=False
        )
        prov_dict = prov.to_dict()
        self.assertEqual(models_mod.ProvenanceV1.from_dict(prov_dict), prov)

        gate = models_mod.ValidityGateV1(is_finite=True, is_valid=True, flags=0)
        gate_dict = gate.to_dict()
        self.assertEqual(models_mod.ValidityGateV1.from_dict(gate_dict), gate)

        env = models_mod.EvidenceEnvelopeV1(
            payload_type="RawSensorSample",
            timestamp=ts,
            provenance=prov,
            payload={"values": [0.1, 0.2, 9.8]},
            validity_gate=gate
        )
        env_dict = env.to_dict()
        self.assertEqual(models_mod.EvidenceEnvelopeV1.from_dict(env_dict), env)


    def _load_codegen_module(self):
        spec = importlib.util.spec_from_file_location("ci_generate_contract_bindings", self.ci_script)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    def test_schema_field_change_affects_generated_output(self):
        """Model generation must be driven by the parsed schemas, not by a
        hard-coded field list. Adding a field to a canonical common schema
        must show up in the generated C++, Python, and Kotlin models."""
        codegen = self._load_codegen_module()
        base_schemas = codegen.load_schemas()

        changed_schemas = copy.deepcopy(base_schemas)
        provenance_schema = changed_schemas["provenance_v1.schema.json"]
        provenance_schema["properties"]["mount_hint"] = {
            "type": "string",
            "minLength": 1,
        }
        provenance_schema["required"].append("mount_hint")

        base_cpp = codegen.generate_cpp_models(base_schemas)
        changed_cpp = codegen.generate_cpp_models(changed_schemas)
        self.assertNotEqual(base_cpp, changed_cpp, "Changing a schema field must change generated C++ output")
        self.assertIn("mount_hint", changed_cpp)
        self.assertNotIn("mount_hint", base_cpp)

        base_py = codegen.generate_python_models(base_schemas)
        changed_py = codegen.generate_python_models(changed_schemas)
        self.assertNotEqual(base_py, changed_py, "Changing a schema field must change generated Python output")
        self.assertIn("mount_hint", changed_py)

        base_kt = codegen.generate_kotlin_models(base_schemas)
        changed_kt = codegen.generate_kotlin_models(changed_schemas)
        self.assertNotEqual(base_kt, changed_kt, "Changing a schema field must change generated Kotlin output")
        self.assertIn("mountHint", changed_kt)

    def test_provenance_type_enum_values_are_schema_driven(self):
        """ProvenanceTypeV1's members must come from
        provenance_v1.schema.json's provenance_type.enum, not a hard-coded
        list, so a schema change to that enum can't leave the generated
        enum silently stale while --check still passes."""
        codegen = self._load_codegen_module()
        base_schemas = codegen.load_schemas()
        base_enums = codegen.load_enums()

        changed_schemas = copy.deepcopy(base_schemas)
        changed_schemas["provenance_v1.schema.json"]["properties"]["provenance_type"]["enum"].append(
            "SIMULATED_FUTURE_SOURCE"
        )

        base_cpp = codegen.generate_cpp_enums(base_enums, base_schemas)
        changed_cpp = codegen.generate_cpp_enums(base_enums, changed_schemas)
        self.assertNotEqual(base_cpp, changed_cpp, "Changing provenance_type's enum must change generated C++ enums")
        self.assertIn("SIMULATED_FUTURE_SOURCE", changed_cpp)
        self.assertNotIn("SIMULATED_FUTURE_SOURCE", base_cpp)

        base_py = codegen.generate_python_enums(base_enums, base_schemas)
        changed_py = codegen.generate_python_enums(base_enums, changed_schemas)
        self.assertNotEqual(base_py, changed_py, "Changing provenance_type's enum must change generated Python enums")
        self.assertIn("SIMULATED_FUTURE_SOURCE", changed_py)

        base_kt = codegen.generate_kotlin_enums(base_enums, base_schemas)
        changed_kt = codegen.generate_kotlin_enums(base_enums, changed_schemas)
        self.assertNotEqual(base_kt, changed_kt, "Changing provenance_type's enum must change generated Kotlin enums")
        self.assertIn("SIMULATED_FUTURE_SOURCE", changed_kt)

    def test_check_mode_detects_byte_level_drift(self):
        """--check must compare raw bytes, not text-normalized content, so
        e.g. CRLF line endings introduced by an editor are caught as drift
        the same way the idempotency test would catch them."""
        target = self.generated_dir / "cpp" / "enums.hpp"
        original_bytes = target.read_bytes()
        try:
            target.write_bytes(original_bytes.replace(b"\n", b"\r\n"))
            result = subprocess.run(
                [sys.executable, str(self.ci_script), "--check"],
                cwd=self.root,
                capture_output=True,
                text=True,
            )
            self.assertNotEqual(result.returncode, 0, "CRLF drift must be reported as drift, not silently accepted")
            self.assertIn("drift", result.stderr.lower())
        finally:
            target.write_bytes(original_bytes)

if __name__ == "__main__":
    unittest.main()
