# Auto-generated by ci/generate_contract_bindings.py. DO NOT EDIT.
# Source schemas: contracts/enums/*.json
# Generator version: 1.0.0-bootstrap
# Deterministic command: python ci/generate_contract_bindings.py

from enum import Enum

class AlignmentStatusV1(str, Enum):
    UNINITIALIZED = "UNINITIALIZED"
    VALID = "VALID"
    UNCERTAIN = "UNCERTAIN"
    SLIP_SUSPECTED = "SLIP_SUSPECTED"


class DisplayModeV1(str, Enum):
    LIVE_DEVICE = "LIVE_DEVICE"
    DETERMINISTIC_REPLAY = "DETERMINISTIC_REPLAY"


class HealthIntegrityStateV1(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    CANDIDATE_RETURN = "CANDIDATE_RETURN"


class MapStatusV1(str, Enum):
    MISSING = "MISSING"
    NO_CANDIDATE = "NO_CANDIDATE"
    AMBIGUOUS = "AMBIGUOUS"
    CLEAR = "CLEAR"
    FAILED = "FAILED"


class ModelStatusV1(str, Enum):
    DISABLED = "DISABLED"
    LOADING = "LOADING"
    SHADOW = "SHADOW"
    ELIGIBLE = "ELIGIBLE"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class NavigationModeV1(str, Enum):
    INITIALIZING = "INITIALIZING"
    GNSS_AIDED = "GNSS_AIDED"
    DEGRADED = "DEGRADED"
    BLACKOUT_DR = "BLACKOUT_DR"
    REACQUIRING = "REACQUIRING"
    FAULT = "FAULT"


class ProvenanceClassificationV1(str, Enum):
    LIVE_DEVICE = "LIVE_DEVICE"
    DETERMINISTIC_REPLAY = "DETERMINISTIC_REPLAY"


class ProvenanceTypeV1(str, Enum):
    LIVE_DEVICE = "LIVE_DEVICE"
    DETERMINISTIC_REPLAY = "DETERMINISTIC_REPLAY"
    LIVE = "LIVE"
    REPLAY = "REPLAY"


class ReacquisitionStatusV1(str, Enum):
    IDLE = "IDLE"
    SCREENING = "SCREENING"
    DWELL = "DWELL"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class RecordingStatusV1(str, Enum):
    STARTING = "STARTING"
    HEALTHY = "HEALTHY"
    EVIDENCE_DEGRADED = "EVIDENCE_DEGRADED"
    LOW_STORAGE = "LOW_STORAGE"
    INCOMPLETE = "INCOMPLETE"
    COMPLETE = "COMPLETE"


class SensorStatusV1(str, Enum):
    AVAILABLE = "AVAILABLE"
    PARTIAL = "PARTIAL"
    GAP = "GAP"
    MISSING_MANDATORY = "MISSING_MANDATORY"
    FAILED = "FAILED"
