# Auto-generated by ci/generate_contract_bindings.py. DO NOT EDIT.
# Source schemas: contracts/schemas/common/*.schema.json
# Generator version: 1.0.0-bootstrap
# Deterministic command: python ci/generate_contract_bindings.py

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .enums import ProvenanceTypeV1


@dataclass(frozen=True)
class TimestampV1:
    epoch_ns: int
    arrival_elapsed_realtime_ns: int
    clock_id: str
    source_timestamp_ns: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        res: Dict[str, Any] = {
            "epoch_ns": self.epoch_ns,
            "arrival_elapsed_realtime_ns": self.arrival_elapsed_realtime_ns,
            "clock_id": self.clock_id,
        }
        if self.source_timestamp_ns is not None:
            res["source_timestamp_ns"] = self.source_timestamp_ns
        return res

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> TimestampV1:
        return cls(
            epoch_ns=int(data["epoch_ns"]),
            arrival_elapsed_realtime_ns=int(data["arrival_elapsed_realtime_ns"]),
            source_timestamp_ns=data.get("source_timestamp_ns"),
            clock_id=str(data["clock_id"]),
        )


@dataclass(frozen=True)
class ProvenanceV1:
    evidence_id: str
    session_id: str
    stream_id: str
    device_id: Optional[str] = None
    build_id: Optional[str] = None
    provenance_type: ProvenanceTypeV1 = ProvenanceTypeV1.LIVE_DEVICE
    synthetic: bool = False
    contributing_evidence_ids: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        res: Dict[str, Any] = {
            "evidence_id": self.evidence_id,
            "session_id": self.session_id,
            "stream_id": self.stream_id,
            "provenance_type": self.provenance_type.value if hasattr(self.provenance_type, "value") else str(self.provenance_type),
            "synthetic": self.synthetic,
            "contributing_evidence_ids": list(self.contributing_evidence_ids),
        }
        if self.device_id is not None:
            res["device_id"] = self.device_id
        if self.build_id is not None:
            res["build_id"] = self.build_id
        return res

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> ProvenanceV1:
        return cls(
            evidence_id=str(data["evidence_id"]),
            session_id=str(data["session_id"]),
            stream_id=str(data["stream_id"]),
            device_id=data.get("device_id"),
            build_id=data.get("build_id"),
            provenance_type=ProvenanceTypeV1(data.get("provenance_type", "LIVE_DEVICE")),
            synthetic=bool(data.get("synthetic", False)),
            contributing_evidence_ids=list(data.get("contributing_evidence_ids", [])),
        )


@dataclass(frozen=True)
class ValidityGateV1:
    is_finite: bool = True
    is_valid: bool = True
    rejection_code: Optional[str] = None
    flags: int = 0

    def to_dict(self) -> Dict[str, Any]:
        res: Dict[str, Any] = {
            "is_finite": self.is_finite,
            "is_valid": self.is_valid,
            "flags": self.flags,
        }
        if self.rejection_code is not None:
            res["rejection_code"] = self.rejection_code
        return res

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> ValidityGateV1:
        return cls(
            is_finite=bool(data.get("is_finite", True)),
            is_valid=bool(data.get("is_valid", True)),
            rejection_code=data.get("rejection_code"),
            flags=int(data.get("flags", 0)),
        )


@dataclass(frozen=True)
class EvidenceEnvelopeV1:
    payload_type: str
    timestamp: TimestampV1
    provenance: ProvenanceV1
    payload: Dict[str, Any]
    validity_gate: ValidityGateV1
    schema_version: int = 1

    def to_dict(self) -> Dict[str, Any]:
        res: Dict[str, Any] = {
            "schema_version": self.schema_version,
            "payload_type": self.payload_type,
            "timestamp": self.timestamp.to_dict(),
            "provenance": self.provenance.to_dict(),
            "payload": self.payload,
            "validity_gate": self.validity_gate.to_dict(),
        }
        return res

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> EvidenceEnvelopeV1:
        return cls(
            schema_version=int(data.get("schema_version", 1)),
            payload_type=str(data["payload_type"]),
            timestamp=TimestampV1.from_dict(data["timestamp"]),
            provenance=ProvenanceV1.from_dict(data["provenance"]),
            payload=dict(data["payload"]),
            validity_gate=ValidityGateV1.from_dict(data["validity_gate"]),
        )
