// Auto-generated by ci/generate_contract_bindings.py. DO NOT EDIT.
// Source schemas: contracts/schemas/common/*.schema.json
// Generator version: 1.0.0-bootstrap
// Deterministic command: python ci/generate_contract_bindings.py

package org.sih26168.contracts.models

import org.sih26168.contracts.enums.ProvenanceTypeV1

data class TimestampV1(
    val epochNs: Long,
    val arrivalElapsedRealtimeNs: Long,
    val clockId: String,
    val sourceTimestampNs: Long? = null
)

data class ProvenanceV1(
    val evidenceId: String,
    val sessionId: String,
    val streamId: String,
    val deviceId: String? = null,
    val buildId: String? = null,
    val provenanceType: ProvenanceTypeV1 = ProvenanceTypeV1.LIVE_DEVICE,
    val synthetic: Boolean = false,
    val contributingEvidenceIds: List<String> = emptyList()
)

data class ValidityGateV1(
    val isFinite: Boolean = true,
    val isValid: Boolean = true,
    val rejectionCode: String? = null,
    val flags: Long = 0L
)

data class EvidenceEnvelopeV1<T>(
    val payloadType: String,
    val timestamp: TimestampV1,
    val provenance: ProvenanceV1,
    val payload: T,
    val validityGate: ValidityGateV1,
    val schemaVersion: Long = 1L
)
