// Auto-generated by ci/generate_contract_bindings.py. DO NOT EDIT.
// Source schemas: contracts/enums/*.json
// Generator version: 1.0.0-bootstrap
// Deterministic command: python ci/generate_contract_bindings.py

#pragma once

#include <cstdint>
#include <optional>
#include <string_view>

namespace sih26168::contracts {

enum class AlignmentStatusV1 : uint8_t {
    UNINITIALIZED,
    VALID,
    UNCERTAIN,
    SLIP_SUSPECTED,
};

[[nodiscard]] constexpr std::string_view to_string(AlignmentStatusV1 value) noexcept {
    switch (value) {
        case AlignmentStatusV1::UNINITIALIZED: return "UNINITIALIZED";
        case AlignmentStatusV1::VALID: return "VALID";
        case AlignmentStatusV1::UNCERTAIN: return "UNCERTAIN";
        case AlignmentStatusV1::SLIP_SUSPECTED: return "SLIP_SUSPECTED";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<AlignmentStatusV1> parse_AlignmentStatusV1(std::string_view str) noexcept {
    if (str == "UNINITIALIZED") return AlignmentStatusV1::UNINITIALIZED;
    if (str == "VALID") return AlignmentStatusV1::VALID;
    if (str == "UNCERTAIN") return AlignmentStatusV1::UNCERTAIN;
    if (str == "SLIP_SUSPECTED") return AlignmentStatusV1::SLIP_SUSPECTED;
    return std::nullopt;
}

enum class DisplayModeV1 : uint8_t {
    LIVE_DEVICE,
    DETERMINISTIC_REPLAY,
};

[[nodiscard]] constexpr std::string_view to_string(DisplayModeV1 value) noexcept {
    switch (value) {
        case DisplayModeV1::LIVE_DEVICE: return "LIVE_DEVICE";
        case DisplayModeV1::DETERMINISTIC_REPLAY: return "DETERMINISTIC_REPLAY";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<DisplayModeV1> parse_DisplayModeV1(std::string_view str) noexcept {
    if (str == "LIVE_DEVICE") return DisplayModeV1::LIVE_DEVICE;
    if (str == "DETERMINISTIC_REPLAY") return DisplayModeV1::DETERMINISTIC_REPLAY;
    return std::nullopt;
}

enum class HealthIntegrityStateV1 : uint8_t {
    HEALTHY,
    DEGRADED,
    UNAVAILABLE,
    CANDIDATE_RETURN,
};

[[nodiscard]] constexpr std::string_view to_string(HealthIntegrityStateV1 value) noexcept {
    switch (value) {
        case HealthIntegrityStateV1::HEALTHY: return "HEALTHY";
        case HealthIntegrityStateV1::DEGRADED: return "DEGRADED";
        case HealthIntegrityStateV1::UNAVAILABLE: return "UNAVAILABLE";
        case HealthIntegrityStateV1::CANDIDATE_RETURN: return "CANDIDATE_RETURN";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<HealthIntegrityStateV1> parse_HealthIntegrityStateV1(std::string_view str) noexcept {
    if (str == "HEALTHY") return HealthIntegrityStateV1::HEALTHY;
    if (str == "DEGRADED") return HealthIntegrityStateV1::DEGRADED;
    if (str == "UNAVAILABLE") return HealthIntegrityStateV1::UNAVAILABLE;
    if (str == "CANDIDATE_RETURN") return HealthIntegrityStateV1::CANDIDATE_RETURN;
    return std::nullopt;
}

enum class MapStatusV1 : uint8_t {
    MISSING,
    NO_CANDIDATE,
    AMBIGUOUS,
    CLEAR,
    FAILED,
};

[[nodiscard]] constexpr std::string_view to_string(MapStatusV1 value) noexcept {
    switch (value) {
        case MapStatusV1::MISSING: return "MISSING";
        case MapStatusV1::NO_CANDIDATE: return "NO_CANDIDATE";
        case MapStatusV1::AMBIGUOUS: return "AMBIGUOUS";
        case MapStatusV1::CLEAR: return "CLEAR";
        case MapStatusV1::FAILED: return "FAILED";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<MapStatusV1> parse_MapStatusV1(std::string_view str) noexcept {
    if (str == "MISSING") return MapStatusV1::MISSING;
    if (str == "NO_CANDIDATE") return MapStatusV1::NO_CANDIDATE;
    if (str == "AMBIGUOUS") return MapStatusV1::AMBIGUOUS;
    if (str == "CLEAR") return MapStatusV1::CLEAR;
    if (str == "FAILED") return MapStatusV1::FAILED;
    return std::nullopt;
}

enum class ModelStatusV1 : uint8_t {
    DISABLED,
    LOADING,
    SHADOW,
    ELIGIBLE,
    REJECTED,
    FAILED,
};

[[nodiscard]] constexpr std::string_view to_string(ModelStatusV1 value) noexcept {
    switch (value) {
        case ModelStatusV1::DISABLED: return "DISABLED";
        case ModelStatusV1::LOADING: return "LOADING";
        case ModelStatusV1::SHADOW: return "SHADOW";
        case ModelStatusV1::ELIGIBLE: return "ELIGIBLE";
        case ModelStatusV1::REJECTED: return "REJECTED";
        case ModelStatusV1::FAILED: return "FAILED";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<ModelStatusV1> parse_ModelStatusV1(std::string_view str) noexcept {
    if (str == "DISABLED") return ModelStatusV1::DISABLED;
    if (str == "LOADING") return ModelStatusV1::LOADING;
    if (str == "SHADOW") return ModelStatusV1::SHADOW;
    if (str == "ELIGIBLE") return ModelStatusV1::ELIGIBLE;
    if (str == "REJECTED") return ModelStatusV1::REJECTED;
    if (str == "FAILED") return ModelStatusV1::FAILED;
    return std::nullopt;
}

enum class NavigationModeV1 : uint8_t {
    INITIALIZING,
    GNSS_AIDED,
    DEGRADED,
    BLACKOUT_DR,
    REACQUIRING,
    FAULT,
};

[[nodiscard]] constexpr std::string_view to_string(NavigationModeV1 value) noexcept {
    switch (value) {
        case NavigationModeV1::INITIALIZING: return "INITIALIZING";
        case NavigationModeV1::GNSS_AIDED: return "GNSS_AIDED";
        case NavigationModeV1::DEGRADED: return "DEGRADED";
        case NavigationModeV1::BLACKOUT_DR: return "BLACKOUT_DR";
        case NavigationModeV1::REACQUIRING: return "REACQUIRING";
        case NavigationModeV1::FAULT: return "FAULT";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<NavigationModeV1> parse_NavigationModeV1(std::string_view str) noexcept {
    if (str == "INITIALIZING") return NavigationModeV1::INITIALIZING;
    if (str == "GNSS_AIDED") return NavigationModeV1::GNSS_AIDED;
    if (str == "DEGRADED") return NavigationModeV1::DEGRADED;
    if (str == "BLACKOUT_DR") return NavigationModeV1::BLACKOUT_DR;
    if (str == "REACQUIRING") return NavigationModeV1::REACQUIRING;
    if (str == "FAULT") return NavigationModeV1::FAULT;
    return std::nullopt;
}

enum class ProvenanceClassificationV1 : uint8_t {
    LIVE_DEVICE,
    DETERMINISTIC_REPLAY,
};

[[nodiscard]] constexpr std::string_view to_string(ProvenanceClassificationV1 value) noexcept {
    switch (value) {
        case ProvenanceClassificationV1::LIVE_DEVICE: return "LIVE_DEVICE";
        case ProvenanceClassificationV1::DETERMINISTIC_REPLAY: return "DETERMINISTIC_REPLAY";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<ProvenanceClassificationV1> parse_ProvenanceClassificationV1(std::string_view str) noexcept {
    if (str == "LIVE_DEVICE") return ProvenanceClassificationV1::LIVE_DEVICE;
    if (str == "DETERMINISTIC_REPLAY") return ProvenanceClassificationV1::DETERMINISTIC_REPLAY;
    return std::nullopt;
}

enum class ProvenanceTypeV1 : uint8_t {
    LIVE_DEVICE,
    DETERMINISTIC_REPLAY,
    LIVE,
    REPLAY,
};

[[nodiscard]] constexpr std::string_view to_string(ProvenanceTypeV1 value) noexcept {
    switch (value) {
        case ProvenanceTypeV1::LIVE_DEVICE: return "LIVE_DEVICE";
        case ProvenanceTypeV1::DETERMINISTIC_REPLAY: return "DETERMINISTIC_REPLAY";
        case ProvenanceTypeV1::LIVE: return "LIVE";
        case ProvenanceTypeV1::REPLAY: return "REPLAY";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<ProvenanceTypeV1> parse_ProvenanceTypeV1(std::string_view str) noexcept {
    if (str == "LIVE_DEVICE") return ProvenanceTypeV1::LIVE_DEVICE;
    if (str == "DETERMINISTIC_REPLAY") return ProvenanceTypeV1::DETERMINISTIC_REPLAY;
    if (str == "LIVE") return ProvenanceTypeV1::LIVE;
    if (str == "REPLAY") return ProvenanceTypeV1::REPLAY;
    return std::nullopt;
}

enum class ReacquisitionStatusV1 : uint8_t {
    IDLE,
    SCREENING,
    DWELL,
    ACCEPTED,
    REJECTED,
};

[[nodiscard]] constexpr std::string_view to_string(ReacquisitionStatusV1 value) noexcept {
    switch (value) {
        case ReacquisitionStatusV1::IDLE: return "IDLE";
        case ReacquisitionStatusV1::SCREENING: return "SCREENING";
        case ReacquisitionStatusV1::DWELL: return "DWELL";
        case ReacquisitionStatusV1::ACCEPTED: return "ACCEPTED";
        case ReacquisitionStatusV1::REJECTED: return "REJECTED";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<ReacquisitionStatusV1> parse_ReacquisitionStatusV1(std::string_view str) noexcept {
    if (str == "IDLE") return ReacquisitionStatusV1::IDLE;
    if (str == "SCREENING") return ReacquisitionStatusV1::SCREENING;
    if (str == "DWELL") return ReacquisitionStatusV1::DWELL;
    if (str == "ACCEPTED") return ReacquisitionStatusV1::ACCEPTED;
    if (str == "REJECTED") return ReacquisitionStatusV1::REJECTED;
    return std::nullopt;
}

enum class RecordingStatusV1 : uint8_t {
    STARTING,
    HEALTHY,
    EVIDENCE_DEGRADED,
    LOW_STORAGE,
    INCOMPLETE,
    COMPLETE,
};

[[nodiscard]] constexpr std::string_view to_string(RecordingStatusV1 value) noexcept {
    switch (value) {
        case RecordingStatusV1::STARTING: return "STARTING";
        case RecordingStatusV1::HEALTHY: return "HEALTHY";
        case RecordingStatusV1::EVIDENCE_DEGRADED: return "EVIDENCE_DEGRADED";
        case RecordingStatusV1::LOW_STORAGE: return "LOW_STORAGE";
        case RecordingStatusV1::INCOMPLETE: return "INCOMPLETE";
        case RecordingStatusV1::COMPLETE: return "COMPLETE";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<RecordingStatusV1> parse_RecordingStatusV1(std::string_view str) noexcept {
    if (str == "STARTING") return RecordingStatusV1::STARTING;
    if (str == "HEALTHY") return RecordingStatusV1::HEALTHY;
    if (str == "EVIDENCE_DEGRADED") return RecordingStatusV1::EVIDENCE_DEGRADED;
    if (str == "LOW_STORAGE") return RecordingStatusV1::LOW_STORAGE;
    if (str == "INCOMPLETE") return RecordingStatusV1::INCOMPLETE;
    if (str == "COMPLETE") return RecordingStatusV1::COMPLETE;
    return std::nullopt;
}

enum class SensorStatusV1 : uint8_t {
    AVAILABLE,
    PARTIAL,
    GAP,
    MISSING_MANDATORY,
    FAILED,
};

[[nodiscard]] constexpr std::string_view to_string(SensorStatusV1 value) noexcept {
    switch (value) {
        case SensorStatusV1::AVAILABLE: return "AVAILABLE";
        case SensorStatusV1::PARTIAL: return "PARTIAL";
        case SensorStatusV1::GAP: return "GAP";
        case SensorStatusV1::MISSING_MANDATORY: return "MISSING_MANDATORY";
        case SensorStatusV1::FAILED: return "FAILED";
        default: return "UNKNOWN";
    }
}

[[nodiscard]] constexpr std::optional<SensorStatusV1> parse_SensorStatusV1(std::string_view str) noexcept {
    if (str == "AVAILABLE") return SensorStatusV1::AVAILABLE;
    if (str == "PARTIAL") return SensorStatusV1::PARTIAL;
    if (str == "GAP") return SensorStatusV1::GAP;
    if (str == "MISSING_MANDATORY") return SensorStatusV1::MISSING_MANDATORY;
    if (str == "FAILED") return SensorStatusV1::FAILED;
    return std::nullopt;
}

} // namespace sih26168::contracts
