// Auto-generated by ci/generate_contract_bindings.py. DO NOT EDIT.
// Source schemas: contracts/schemas/common/*.schema.json
// Generator version: 1.0.0-bootstrap
// Deterministic command: python ci/generate_contract_bindings.py

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include "enums.hpp"

namespace sih26168::contracts {

struct TimestampV1 {
    int64_t epoch_ns{0};
    int64_t arrival_elapsed_realtime_ns{0};
    std::optional<int64_t> source_timestamp_ns{std::nullopt};
    std::string clock_id{};
};

struct ProvenanceV1 {
    std::string evidence_id{};
    std::string session_id{};
    std::string stream_id{};
    std::optional<std::string> device_id{std::nullopt};
    std::optional<std::string> build_id{std::nullopt};
    ProvenanceTypeV1 provenance_type{ProvenanceTypeV1::LIVE_DEVICE};
    bool synthetic{false};
    std::vector<std::string> contributing_evidence_ids{};
};

struct ValidityGateV1 {
    bool is_finite{true};
    bool is_valid{true};
    std::optional<std::string> rejection_code{std::nullopt};
    uint32_t flags{0};
};

template <typename PayloadT>
struct EvidenceEnvelopeV1 {
    uint32_t schema_version{1};
    std::string payload_type{};
    TimestampV1 timestamp{};
    ProvenanceV1 provenance{};
    PayloadT payload{};
    ValidityGateV1 validity_gate{};
};

} // namespace sih26168::contracts
