#!/usr/bin/env python3
"""
Authoritative deterministic contract bindings generator for SIH26168.
Implements WP-01.4 as specified by Architecture Revision 3 Component C-20
and contracts/INTERFACE_SCHEMA_PLAN.md.

Produces deterministic native data models in C++20, Python, and Kotlin
from JSON Schema Draft 2020-12 and canonical enum contract definitions.
Adheres strictly to docs/GENERATED_FILE_POLICY.md.

Model generation for the common envelope/timestamp/provenance schemas is
schema-driven: field names, types, optionality and defaults are derived
from the parsed JSON Schema documents in contracts/schemas/common (see
`schema_fields()` and the per-language renderers below), not hand-copied
into this file. Changing a canonical schema's properties therefore changes
the generated bindings; `tools/bootstrap/tests/test_codegen.py::
test_schema_field_change_affects_generated_output` proves this directly.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS_DIR = ROOT / "contracts"
ENUMS_DIR = CONTRACTS_DIR / "enums"
SCHEMAS_DIR = CONTRACTS_DIR / "schemas/common"
VERSION_FILE = CONTRACTS_DIR / "VERSION"
GENERATED_DIR = CONTRACTS_DIR / "generated"

GENERATOR_VERSION = "1.0.0-bootstrap"
COMMAND_TAG = "python ci/generate_contract_bindings.py"

# The normative contract (contracts/INTERFACE_SCHEMA_PLAN.md section 3.3)
# declares the canonical nanosecond timebase fields as signed 64-bit
# integers. Their schemas mark this by setting `maximum` to INT64_MAX;
# any other "integer" property is treated as a 32-bit unsigned value
# (bitmasks, small counters, schema/version numbers).
INT64_MAX = 9223372036854775807

# JSON Schema fields whose properties are enum-typed or reference another
# common schema/inline object don't carry a generated-language type name
# themselves (that's a codegen naming decision, not a schema fact), so
# those mappings are recorded here explicitly.
REF_STRUCT_NAMES = {
    "timestamp_v1.schema.json": "TimestampV1",
    "provenance_v1.schema.json": "ProvenanceV1",
}
ENUM_TYPE_BY_FIELD = {
    "provenance_type": "ProvenanceTypeV1",
}
INLINE_STRUCT_NAMES = {
    "validity_gate": "ValidityGateV1",
}


def get_contract_version() -> str:
    if VERSION_FILE.is_file():
        return VERSION_FILE.read_text(encoding="utf-8").strip()
    return "1.0.0-bootstrap"


def make_header(sources: str, comment_prefix: str = "//") -> str:
    return (
        f"{comment_prefix} Auto-generated by ci/generate_contract_bindings.py. DO NOT EDIT.\n"
        f"{comment_prefix} Source schemas: {sources}\n"
        f"{comment_prefix} Generator version: {GENERATOR_VERSION}\n"
        f"{comment_prefix} Deterministic command: {COMMAND_TAG}\n\n"
    )


def load_enums() -> Dict[str, Dict]:
    enums = {}
    for p in sorted(ENUMS_DIR.glob("*.json")):
        data = json.loads(p.read_text(encoding="utf-8"))
        enums[p.name] = data
    return enums


def load_schemas() -> Dict[str, Dict]:
    schemas = {}
    for p in sorted(SCHEMAS_DIR.glob("*.json")):
        data = json.loads(p.read_text(encoding="utf-8"))
        schemas[p.name] = data
    return schemas


def collect_input_paths() -> List[str]:
    inputs = [VERSION_FILE.relative_to(ROOT).as_posix()]
    for p in sorted(ENUMS_DIR.glob("*.json")):
        inputs.append(p.relative_to(ROOT).as_posix())
    for p in sorted(SCHEMAS_DIR.glob("*.json")):
        inputs.append(p.relative_to(ROOT).as_posix())
    return sorted(inputs)


def generate_contract_version_manifest(version: str, inputs: List[str]) -> str:
    data = {
        "contract_version": version,
        "generated_from": inputs,
    }
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def _provenance_type_enum_values(schemas: Dict[str, Dict]) -> List[str]:
    """ProvenanceTypeV1's authoritative values live in
    provenance_v1.schema.json's `provenance_type` property -- derive them
    from there instead of a hard-coded list, so a schema change to that
    enum can't leave the generated enum silently stale while --check
    still passes.
    """
    return list(schemas["provenance_v1.schema.json"]["properties"]["provenance_type"]["enum"])


def generate_cpp_enums(enums: Dict[str, Dict], schemas: Dict[str, Dict]) -> str:
    out = make_header("contracts/enums/*.json", "//")
    out += "#pragma once\n\n"
    out += "#include <cstdint>\n"
    out += "#include <optional>\n"
    out += "#include <string_view>\n\n"
    out += "namespace sih26168::contracts {\n\n"

    # Enums to generate
    enum_list: List[Tuple[str, List[str]]] = []
    for filename, data in sorted(enums.items()):
        name = data.get("enum_name")
        if name and "values" in data:
            enum_list.append((name, data["values"]))
        elif filename == "navigation_states_v1.json":
            if "provenance" in data:
                enum_list.append(("ProvenanceClassificationV1", data["provenance"]))

    # ProvenanceTypeV1 is not one of the contracts/enums/*.json files -- its
    # authoritative values live in provenance_v1.schema.json, derived below.
    if not any(name == "ProvenanceTypeV1" for name, _ in enum_list):
        enum_list.append(("ProvenanceTypeV1", _provenance_type_enum_values(schemas)))

    for enum_name, values in sorted(enum_list, key=lambda x: x[0]):
        out += f"enum class {enum_name} : uint8_t {{\n"
        for v in values:
            out += f"    {v},\n"
        out += "};\n\n"

        # to_string
        out += f"[[nodiscard]] constexpr std::string_view to_string({enum_name} value) noexcept {{\n"
        out += "    switch (value) {\n"
        for v in values:
            out += f'        case {enum_name}::{v}: return "{v}";\n'
        out += '        default: return "UNKNOWN";\n'
        out += "    }\n"
        out += "}\n\n"

        # parse
        out += f"[[nodiscard]] constexpr std::optional<{enum_name}> parse_{enum_name}(std::string_view str) noexcept {{\n"
        for v in values:
            out += f'    if (str == "{v}") return {enum_name}::{v};\n'
        out += "    return std::nullopt;\n"
        out += "}\n\n"

    out += "} // namespace sih26168::contracts\n"
    return out


# ---------------------------------------------------------------------------
# Schema-driven field extraction shared by the C++, Python, and Kotlin model
# generators. A `SchemaField` mirrors one JSON Schema property: its declared
# type, whether it's `required`, and any `default`/`const` annotation.
#
# Note on optional vs. nullable: JSON Schema's `required` says a field may
# be *absent*; it says nothing about whether a *present* value may be JSON
# `null` (that would be a separate `"type": [T, "null"]` declaration). This
# generator only needs the former -- none of the canonical common schemas
# declare a field nullable in the latter sense -- so `SchemaField.optional`
# (== "not required") drives the generated language's optional-presence
# wrapper (std::optional<T>, Optional[T], T?), and serialization represents
# an absent field by omitting its key, never by emitting a literal null.
# ---------------------------------------------------------------------------

class SchemaField:
    __slots__ = ("name", "required", "kind", "prop")

    def __init__(self, name: str, required: bool, kind: str, prop: Dict):
        self.name = name
        self.required = required
        self.kind = kind
        self.prop = prop

    @property
    def optional(self) -> bool:
        """True if this field may be absent from a serialized payload.

        Presence, not nullability -- see the module-level note above.
        """
        return not self.required

    @property
    def has_default(self) -> bool:
        return "default" in self.prop or "const" in self.prop

    @property
    def default(self) -> Any:
        if "default" in self.prop:
            return self.prop["default"]
        return self.prop.get("const")


def _field_kind(prop: Dict) -> str:
    if "$ref" in prop:
        return "ref"

    t = prop.get("type")
    if t == "integer":
        return "int64" if prop.get("maximum") == INT64_MAX else "int32"
    if t == "string":
        return "enum" if "enum" in prop else "string"
    if t == "boolean":
        return "bool"
    if t == "array":
        items = prop.get("items", {})
        if items.get("type") == "string":
            return "array_string"
        raise ValueError(f"Unsupported array item schema for codegen: {items}")
    if t == "object":
        return "object_inline" if "properties" in prop else "object_generic"
    raise ValueError(f"Unsupported schema property type for codegen: {prop}")


def schema_fields(schema: Dict) -> List[SchemaField]:
    """Extract fields from a JSON Schema object, in declaration order.

    Both `contracts/schemas/common/*.schema.json` top-level documents and
    inline nested object schemas (e.g. EvidenceEnvelopeV1's `validity_gate`
    property) are supported, since both are plain `{"properties": ...,
    "required": [...]}` shapes.
    """
    required = set(schema.get("required", []))
    fields = []
    for name, prop in schema.get("properties", {}).items():
        fields.append(SchemaField(name, name in required, _field_kind(prop), prop))
    return fields


def _effective_has_default(f: SchemaField) -> bool:
    """True if the generated binding gives this field a default value.

    Every field the schema doesn't mark required ends up with *some*
    default (empty/zero, or Optional[...] = None) in the generated
    language; a required field only gets one if the schema explicitly
    says so via `default`/`const`.
    """
    if f.has_default:
        return True
    return f.optional


def _grouped_fields(fields: List[SchemaField]) -> List[SchemaField]:
    """Reorder so fields with no default precede fields that have one.

    Python dataclasses and Kotlin data classes both require constructor
    parameters without a default to precede those with one; C++ aggregate
    initialization has no such constraint, so C++ rendering uses the raw
    schema declaration order instead.
    """
    no_default = [f for f in fields if not _effective_has_default(f)]
    with_default = [f for f in fields if _effective_has_default(f)]
    return no_default + with_default


# ---------------------------------------------------------------------------
# C++ model generation
# ---------------------------------------------------------------------------

def _cpp_base_type(f: SchemaField) -> str:
    if f.kind == "ref":
        return REF_STRUCT_NAMES[f.prop["$ref"]]
    if f.kind == "object_inline":
        return INLINE_STRUCT_NAMES[f.name]
    if f.kind == "enum":
        return ENUM_TYPE_BY_FIELD[f.name]
    if f.kind == "int64":
        return "int64_t"
    if f.kind == "int32":
        return "uint32_t"
    if f.kind == "string":
        return "std::string"
    if f.kind == "bool":
        return "bool"
    if f.kind == "array_string":
        return "std::vector<std::string>"
    if f.kind == "object_generic":
        return "PayloadT"
    raise ValueError(f"Unhandled kind for C++ type: {f.kind}")


def _cpp_field_type(f: SchemaField) -> str:
    base = _cpp_base_type(f)
    # Repeated fields represent "absent" as empty, like Python's
    # field(default_factory=list) and Kotlin's emptyList() below -- an
    # optional array doesn't need a second, redundant absence signal on
    # top of "zero elements".
    if f.optional and f.kind != "array_string":
        return f"std::optional<{base}>"
    return base


def _cpp_field_default(f: SchemaField) -> str:
    if f.optional and f.kind != "array_string":
        return "std::nullopt"
    if f.kind in ("array_string", "ref", "object_inline", "object_generic", "string"):
        if f.kind == "string" and f.has_default:
            return json.dumps(f.default)
        return ""
    if f.kind == "bool":
        val = f.default if f.has_default else False
        return "true" if val else "false"
    if f.kind in ("int32", "int64"):
        val = f.default if f.has_default else 0
        return str(val)
    if f.kind == "enum":
        val = f.default if f.has_default else f.prop["enum"][0]
        return f"{ENUM_TYPE_BY_FIELD[f.name]}::{val}"
    raise ValueError(f"Unhandled kind for C++ default: {f.kind}")


def _cpp_struct_body(fields: List[SchemaField]) -> List[str]:
    lines = []
    for f in fields:
        cpp_type = _cpp_field_type(f)
        default = _cpp_field_default(f)
        lines.append(f"    {cpp_type} {f.name}{{{default}}};")
    return lines


def generate_cpp_models(schemas: Dict[str, Dict]) -> str:
    ts_fields = schema_fields(schemas["timestamp_v1.schema.json"])
    prov_fields = schema_fields(schemas["provenance_v1.schema.json"])
    envelope_schema = schemas["evidence_envelope_v1.schema.json"]
    gate_fields = schema_fields(envelope_schema["properties"]["validity_gate"])
    envelope_fields = schema_fields(envelope_schema)

    out = make_header("contracts/schemas/common/*.schema.json", "//")
    out += "#pragma once\n\n"
    out += "#include <cstdint>\n"
    out += "#include <optional>\n"
    out += "#include <string>\n"
    out += "#include <vector>\n"
    out += '#include "enums.hpp"\n\n'
    out += "namespace sih26168::contracts {\n\n"

    out += "struct TimestampV1 {\n"
    out += "\n".join(_cpp_struct_body(ts_fields)) + "\n"
    out += "};\n\n"

    out += "struct ProvenanceV1 {\n"
    out += "\n".join(_cpp_struct_body(prov_fields)) + "\n"
    out += "};\n\n"

    out += "struct ValidityGateV1 {\n"
    out += "\n".join(_cpp_struct_body(gate_fields)) + "\n"
    out += "};\n\n"

    # The envelope's payload is domain-specific (RawSensorSample,
    # LocationGnssFix, ...): EvidenceEnvelopeV1 is a template so each
    # concrete instantiation carries a typed payload member, matching the
    # schema's `payload` (required, type: object) property instead of
    # omitting it.
    out += "template <typename PayloadT>\n"
    out += "struct EvidenceEnvelopeV1 {\n"
    out += "\n".join(_cpp_struct_body(envelope_fields)) + "\n"
    out += "};\n\n"

    out += "} // namespace sih26168::contracts\n"
    return out


# ---------------------------------------------------------------------------
# Python model generation
# ---------------------------------------------------------------------------

def _py_type_annotation(f: SchemaField) -> str:
    if f.kind == "ref":
        base = REF_STRUCT_NAMES[f.prop["$ref"]]
    elif f.kind == "object_inline":
        base = INLINE_STRUCT_NAMES[f.name]
    elif f.kind == "enum":
        base = ENUM_TYPE_BY_FIELD[f.name]
    elif f.kind in ("int32", "int64"):
        base = "int"
    elif f.kind == "string":
        base = "str"
    elif f.kind == "bool":
        base = "bool"
    elif f.kind == "array_string":
        return "List[str]"
    elif f.kind == "object_generic":
        return "Dict[str, Any]"
    else:
        raise ValueError(f"Unhandled kind for Python type: {f.kind}")
    if f.optional:
        return f"Optional[{base}]"
    return base


def _py_default_literal(f: SchemaField) -> Optional[str]:
    if f.kind == "array_string":
        return None  # rendered via field(default_factory=list)
    if not _effective_has_default(f):
        return None
    if f.optional and not f.has_default:
        return "None"
    if f.has_default:
        val = f.default
        if f.kind == "bool":
            return "True" if val else "False"
        if f.kind == "enum":
            return f"{ENUM_TYPE_BY_FIELD[f.name]}.{val}"
        if f.kind in ("int32", "int64"):
            return str(val)
        if f.kind == "string":
            return json.dumps(val)
        raise ValueError(f"Unhandled kind for Python default: {f.kind}")
    if f.kind == "bool":
        return "False"
    if f.kind in ("int32", "int64"):
        return "0"
    if f.kind == "string":
        return '""'
    raise ValueError(f"Unhandled kind for Python fallback default: {f.kind}")


def _py_to_dict_expr(f: SchemaField) -> str:
    if f.kind in ("ref", "object_inline"):
        return f"self.{f.name}.to_dict()"
    if f.kind == "enum":
        return f'self.{f.name}.value if hasattr(self.{f.name}, "value") else str(self.{f.name})'
    if f.kind == "array_string":
        return f"list(self.{f.name})"
    return f"self.{f.name}"


def _py_from_dict_expr(f: SchemaField) -> str:
    key = f.name
    if f.kind == "ref":
        struct_name = REF_STRUCT_NAMES[f.prop["$ref"]]
        return f'{struct_name}.from_dict(data["{key}"])'
    if f.kind == "object_inline":
        struct_name = INLINE_STRUCT_NAMES[f.name]
        return f'{struct_name}.from_dict(data["{key}"])'
    if f.kind == "object_generic":
        return f'dict(data["{key}"])'
    if f.kind == "array_string":
        return f'list(data.get("{key}", []))'
    if f.optional:
        return f'data.get("{key}")'
    if f.kind == "enum":
        enum_type = ENUM_TYPE_BY_FIELD[f.name]
        if f.required and not f.has_default:
            return f'{enum_type}(data["{key}"])'
        default_repr = json.dumps(f.default)
        return f'{enum_type}(data.get("{key}", {default_repr}))'
    caster = {"bool": "bool", "int32": "int", "int64": "int", "string": "str"}[f.kind]
    if f.required and not f.has_default:
        return f'{caster}(data["{key}"])'
    default = f.default if f.has_default else (False if f.kind == "bool" else 0)
    return f'{caster}(data.get("{key}", {default!r}))'


def _py_dataclass(name: str, fields: List[SchemaField]) -> str:
    ordered = _grouped_fields(fields)
    lines = [f"@dataclass(frozen=True)", f"class {name}:"]
    for f in ordered:
        ann = _py_type_annotation(f)
        if f.kind == "array_string":
            lines.append(f"    {f.name}: {ann} = field(default_factory=list)")
            continue
        default = _py_default_literal(f)
        if default is None:
            lines.append(f"    {f.name}: {ann}")
        else:
            lines.append(f"    {f.name}: {ann} = {default}")
    lines.append("")

    lines.append("    def to_dict(self) -> Dict[str, Any]:")
    base_fields = [f for f in fields if not (f.optional and not f.has_default)]
    optional_fields = [f for f in fields if f.optional and not f.has_default]
    lines.append("        res: Dict[str, Any] = {")
    for f in base_fields:
        lines.append(f'            "{f.name}": {_py_to_dict_expr(f)},')
    lines.append("        }")
    for f in optional_fields:
        lines.append(f"        if self.{f.name} is not None:")
        lines.append(f'            res["{f.name}"] = {_py_to_dict_expr(f)}')
    lines.append("        return res")
    lines.append("")

    lines.append("    @classmethod")
    lines.append(f"    def from_dict(cls, data: Dict[str, Any]) -> {name}:")
    lines.append("        return cls(")
    for f in fields:
        lines.append(f"            {f.name}={_py_from_dict_expr(f)},")
    lines.append("        )")

    return "\n".join(lines) + "\n"


def generate_python_models(schemas: Dict[str, Dict]) -> str:
    ts_fields = schema_fields(schemas["timestamp_v1.schema.json"])
    prov_fields = schema_fields(schemas["provenance_v1.schema.json"])
    envelope_schema = schemas["evidence_envelope_v1.schema.json"]
    gate_fields = schema_fields(envelope_schema["properties"]["validity_gate"])
    envelope_fields = schema_fields(envelope_schema)

    out = make_header("contracts/schemas/common/*.schema.json", "#")
    out += "from __future__ import annotations\n\n"
    out += "from dataclasses import dataclass, field\n"
    out += "from typing import Any, Dict, List, Optional\n\n"
    out += "from .enums import ProvenanceTypeV1\n\n\n"

    out += _py_dataclass("TimestampV1", ts_fields) + "\n\n"
    out += _py_dataclass("ProvenanceV1", prov_fields) + "\n\n"
    out += _py_dataclass("ValidityGateV1", gate_fields) + "\n\n"
    out += _py_dataclass("EvidenceEnvelopeV1", envelope_fields)

    return out.rstrip() + "\n"


def generate_python_init() -> str:
    out = make_header("contracts/schemas/common/*.json", "#")
    out += "from .enums import (\n"
    out += "    AlignmentStatusV1,\n"
    out += "    DisplayModeV1,\n"
    out += "    HealthIntegrityStateV1,\n"
    out += "    MapStatusV1,\n"
    out += "    ModelStatusV1,\n"
    out += "    NavigationModeV1,\n"
    out += "    ProvenanceClassificationV1,\n"
    out += "    ProvenanceTypeV1,\n"
    out += "    ReacquisitionStatusV1,\n"
    out += "    RecordingStatusV1,\n"
    out += "    SensorStatusV1,\n"
    out += ")\n"
    out += "from .models import (\n"
    out += "    EvidenceEnvelopeV1,\n"
    out += "    ProvenanceV1,\n"
    out += "    TimestampV1,\n"
    out += "    ValidityGateV1,\n"
    out += ")\n\n"
    out += "__all__ = [\n"
    out += '    "AlignmentStatusV1",\n'
    out += '    "DisplayModeV1",\n'
    out += '    "HealthIntegrityStateV1",\n'
    out += '    "MapStatusV1",\n'
    out += '    "ModelStatusV1",\n'
    out += '    "NavigationModeV1",\n'
    out += '    "ProvenanceClassificationV1",\n'
    out += '    "ProvenanceTypeV1",\n'
    out += '    "ReacquisitionStatusV1",\n'
    out += '    "RecordingStatusV1",\n'
    out += '    "SensorStatusV1",\n'
    out += '    "TimestampV1",\n'
    out += '    "ProvenanceV1",\n'
    out += '    "ValidityGateV1",\n'
    out += '    "EvidenceEnvelopeV1",\n'
    out += "]\n"
    return out


def generate_kotlin_enums(enums: Dict[str, Dict], schemas: Dict[str, Dict]) -> str:
    out = make_header("contracts/enums/*.json", "//")
    out += "package org.sih26168.contracts.enums\n\n"

    enum_list: List[Tuple[str, List[str]]] = []
    for filename, data in sorted(enums.items()):
        name = data.get("enum_name")
        if name and "values" in data:
            enum_list.append((name, data["values"]))
        elif filename == "navigation_states_v1.json":
            if "provenance" in data:
                enum_list.append(("ProvenanceClassificationV1", data["provenance"]))

    if not any(name == "ProvenanceTypeV1" for name, _ in enum_list):
        enum_list.append(("ProvenanceTypeV1", _provenance_type_enum_values(schemas)))

    for enum_name, values in sorted(enum_list, key=lambda x: x[0]):
        out += f"enum class {enum_name} {{\n"
        for v in values:
            out += f"    {v},\n"
        out += "}\n\n"

    return out.rstrip() + "\n"


# ---------------------------------------------------------------------------
# Kotlin model generation
# ---------------------------------------------------------------------------

def _kt_field_name(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _kt_base_type(f: SchemaField) -> str:
    if f.kind == "ref":
        return REF_STRUCT_NAMES[f.prop["$ref"]]
    if f.kind == "object_inline":
        return INLINE_STRUCT_NAMES[f.name]
    if f.kind == "enum":
        return ENUM_TYPE_BY_FIELD[f.name]
    if f.kind in ("int32", "int64"):
        return "Long"
    if f.kind == "string":
        return "String"
    if f.kind == "bool":
        return "Boolean"
    if f.kind == "array_string":
        return "List<String>"
    if f.kind == "object_generic":
        return "T"
    raise ValueError(f"Unhandled kind for Kotlin type: {f.kind}")


def _kt_field_type(f: SchemaField) -> str:
    base = _kt_base_type(f)
    if f.kind == "array_string":
        return base
    if f.optional:
        return f"{base}?"
    return base


def _kt_field_default(f: SchemaField) -> Optional[str]:
    if f.kind == "array_string":
        return "emptyList()"
    if f.optional:
        return "null"
    if not _effective_has_default(f):
        return None
    if f.kind == "bool":
        val = f.default if f.has_default else False
        return "true" if val else "false"
    if f.kind in ("int32", "int64"):
        val = f.default if f.has_default else 0
        return f"{val}L"
    if f.kind == "enum":
        val = f.default if f.has_default else f.prop["enum"][0]
        return f"{ENUM_TYPE_BY_FIELD[f.name]}.{val}"
    if f.kind == "string" and f.has_default:
        return json.dumps(f.default)
    return None


def _kt_data_class(name: str, fields: List[SchemaField], type_param: Optional[str] = None) -> str:
    ordered = _grouped_fields(fields)
    header = f"data class {name}" + (f"<{type_param}>" if type_param else "") + "(\n"
    body_lines = []
    for f in ordered:
        kt_type = _kt_field_type(f)
        default = _kt_field_default(f)
        field_name = _kt_field_name(f.name)
        if default is not None:
            body_lines.append(f"    val {field_name}: {kt_type} = {default}")
        else:
            body_lines.append(f"    val {field_name}: {kt_type}")
    return header + ",\n".join(body_lines) + "\n)\n"


def generate_kotlin_models(schemas: Dict[str, Dict]) -> str:
    ts_fields = schema_fields(schemas["timestamp_v1.schema.json"])
    prov_fields = schema_fields(schemas["provenance_v1.schema.json"])
    envelope_schema = schemas["evidence_envelope_v1.schema.json"]
    gate_fields = schema_fields(envelope_schema["properties"]["validity_gate"])
    envelope_fields = schema_fields(envelope_schema)

    out = make_header("contracts/schemas/common/*.schema.json", "//")
    out += "package org.sih26168.contracts.models\n\n"
    out += "import org.sih26168.contracts.enums.ProvenanceTypeV1\n\n"

    out += _kt_data_class("TimestampV1", ts_fields) + "\n"
    out += _kt_data_class("ProvenanceV1", prov_fields) + "\n"
    out += _kt_data_class("ValidityGateV1", gate_fields) + "\n"
    # Mirrors the C++ template: the payload is domain-specific, so the
    # envelope stays generic over its payload type rather than dropping it.
    out += _kt_data_class("EvidenceEnvelopeV1", envelope_fields, type_param="T")

    return out


def generate_all_bindings() -> Dict[Path, str]:
    version = get_contract_version()
    enums = load_enums()
    schemas = load_schemas()
    inputs = collect_input_paths()

    bindings: Dict[Path, str] = {}

    # 1. Manifest
    bindings[GENERATED_DIR / "contract_version.json"] = generate_contract_version_manifest(version, inputs)

    # 2. C++
    bindings[GENERATED_DIR / "cpp/enums.hpp"] = generate_cpp_enums(enums, schemas)
    bindings[GENERATED_DIR / "cpp/models.hpp"] = generate_cpp_models(schemas)

    # 3. Python
    bindings[GENERATED_DIR / "python/__init__.py"] = generate_python_init()
    bindings[GENERATED_DIR / "python/enums.py"] = generate_python_enums(enums, schemas)
    bindings[GENERATED_DIR / "python/models.py"] = generate_python_models(schemas)

    # 4. Kotlin
    bindings[GENERATED_DIR / "kotlin/Enums.kt"] = generate_kotlin_enums(enums, schemas)
    bindings[GENERATED_DIR / "kotlin/Models.kt"] = generate_kotlin_models(schemas)

    return bindings


def generate_python_enums(enums: Dict[str, Dict], schemas: Dict[str, Dict]) -> str:
    out = make_header("contracts/enums/*.json", "#")
    out += "from enum import Enum\n\n"

    enum_list: List[Tuple[str, List[str]]] = []
    for filename, data in sorted(enums.items()):
        name = data.get("enum_name")
        if name and "values" in data:
            enum_list.append((name, data["values"]))
        elif filename == "navigation_states_v1.json":
            if "provenance" in data:
                enum_list.append(("ProvenanceClassificationV1", data["provenance"]))

    if not any(name == "ProvenanceTypeV1" for name, _ in enum_list):
        enum_list.append(("ProvenanceTypeV1", _provenance_type_enum_values(schemas)))

    for enum_name, values in sorted(enum_list, key=lambda x: x[0]):
        out += f"class {enum_name}(str, Enum):\n"
        for v in values:
            out += f'    {v} = "{v}"\n'
        out += "\n\n"

    return out.rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Deterministic contract bindings generator for C++, Python, and Kotlin."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check on-disk generated bindings against expected output; exits with non-zero on drift.",
    )
    args = parser.parse_args()

    expected_bindings = generate_all_bindings()

    if args.check:
        drift_errors = []
        for path, expected_content in sorted(expected_bindings.items(), key=lambda x: str(x[0])):
            rel_path = path.relative_to(ROOT).as_posix()
            if not path.is_file():
                drift_errors.append(f"missing generated file: {rel_path}")
            else:
                # Compare raw bytes (not read_text()) so line-ending drift
                # (e.g. CRLF vs LF) is caught the same way the idempotency
                # test catches it, instead of being normalized away.
                actual_bytes = path.read_bytes()
                if actual_bytes != expected_content.encode("utf-8"):
                    drift_errors.append(f"drift in generated file: {rel_path}")

        if drift_errors:
            sys.stderr.write("Generated contract bindings drift detected:\n")
            for err in drift_errors:
                sys.stderr.write(f"  - {err}\n")
            sys.exit(1)

        print("PASS: generated contract bindings")
        return 0

    # Generation mode
    for path, content in expected_bindings.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")

    print(f"PASS: successfully generated {len(expected_bindings)} contract binding artifacts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
